import React from "react"

const Table = () => {
  return (
    <div className="col-md-2">
      <table className="tablo">
        <thead>
        <tr>
          <th>Hexa</th>
          <th>Binary</th>
          <th>Octal</th>
          <th>Decimal</th>
        </tr>
        </thead>
  <tbody>
        <tr>
          <td>0</td>
          <td>0000</td>
          <td>0</td>
          <td>0</td>
        </tr>
        <tr>
          <td>1</td>
          <td>0001</td>
          <td>1</td>
          <td>1</td>
        </tr>
        <tr>
          <td>2</td>
          <td>0010</td>
          <td>2</td>
          <td>2</td>
        </tr>
        <tr>
          <td>3</td>
          <td>0011</td>
          <td>3</td>
          <td>3</td>
        </tr>
        <tr>
          <td>4</td>
          <td>0100</td>
          <td>4</td>
          <td>4</td>
        </tr>
        <tr>
          <td>5</td>
          <td>0101</td>
          <td>5</td>
          <td>5</td>
        </tr>
        <tr>
          <td>6</td>
          <td>0110</td>
          <td>6</td>
          <td>6</td>
        </tr>
        <tr>
          <td>7</td>
          <td>0111</td>
          <td>7</td>
          <td>7</td>
        </tr>
        <tr>
          <td>8</td>
          <td>1000</td>
          <td>10</td>
          <td>8</td>
        </tr>
        <tr>
          <td>9</td>
          <td>1001</td>
          <td>11</td>
          <td>9</td>
        </tr>
        <tr>
          <td>A</td>
          <td>1010</td>
          <td>12</td>
          <td>10</td>
        </tr>
        <tr>
          <td>B</td>
          <td>1011</td>
          <td>13</td>
          <td>11</td>
        </tr>
        <tr>
          <td>C</td>
          <td>1100</td>
          <td>14</td>
          <td>12</td>
        </tr>
        <tr>
          <td>D</td>
          <td>1101</td>
          <td>13</td>
          <td>15</td>
        </tr>
        <tr>
          <td>E</td>
          <td>1110</td>
          <td>16</td>
          <td>14</td>
        </tr>
        <tr>
          <td>F</td>
          <td>1111</td>
          <td>17</td>
          <td>15</td>
        </tr>
        </tbody>
      </table>
    </div>
  )
}

export default Table
